'use client';
import {useEffect,useState} from 'react';
import {Orbit,RefreshCw,Layers,ChevronLeft,ChevronRight,Info} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {PolarMap} from '@/components/polar-map';
import {MODELS,isModel,isCycle,supports,type ModelId,type ForecastMeta} from '@/lib/models';
import type {Frame} from '@/lib/grib';
const levels=[10,20,30,50,70,100];
const frameCache=new Map<string,{at:number;frame:Frame}>();
const alt:Record<number,string>={10:'~31 km',20:'~26 km',30:'~24 km',50:'~21 km',70:'~18 km',100:'~16 km'};
const date=(v:string)=>new Date(v).toLocaleString('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).replace(',','');
export default function Home(){
 const [model,setModel]=useState<ModelId>('gfs'),[meta,setMeta]=useState<ForecastMeta|null>(null),[level,setLevel]=useState(10),[hour,setHour]=useState(0),[field,setField]=useState('temperature'),[contours,setContours]=useState(true),[grid,setGrid]=useState(true),[frame,setFrame]=useState<Frame|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[retryAt,setRetryAt]=useState(0),[attempt,setAttempt]=useState(0),[retryTick,setRetryTick]=useState(0);
 const config=MODELS[model],maxHour=config.maxHour,run=meta?.model===model?meta.run:'',cyclic=isCycle(model);
 function chooseModel(value:string){if(!isModel(value))return;setModel(value);if(!supports(value,level))setLevel(MODELS[value].levels[0]);setHour(h=>Math.min(h,MODELS[value].maxHour))}
 function refreshData(){for(const key of frameCache.keys())if(key.startsWith(model+'/'))frameCache.delete(key);setRefresh(v=>v+1)}
 useEffect(()=>{
  const c=new AbortController();setMeta(null);setLoading(true);setError('');setRetryAt(0);
  fetch(`/api/forecast?meta=1&model=${model}`,{signal:AbortSignal.any([c.signal,AbortSignal.timeout(55000)]),cache:'no-cache'}).then(async r=>{const j=await r.json() as ForecastMeta & {error?:string};if(!r.ok)throw Error(j.error);setMeta(j)}).catch(e=>{if(e.name!=='AbortError'){setError(e.name==='TimeoutError'?'Finding the latest forecast took too long. Please retry.':e.message);setLoading(false)}});
  return()=>c.abort();
 },[model,refresh]);
 useEffect(()=>{
  if(!run||!supports(model,level))return;const c=new AbortController(),key=`${model}/${run}/${level}/${hour}`,cached=frameCache.get(key);setError('');setRetryAt(0);
  if(cached&&Date.now()-cached.at<900000){setFrame(cached.frame);setLoading(false);return;}setLoading(true);
  const timer=setTimeout(()=>{fetch(`/api/forecast?model=${model}&run=${encodeURIComponent(run)}&hour=${hour}&level=${level}`,{signal:AbortSignal.any([c.signal,AbortSignal.timeout(180000)])}).then(async r=>{const j=await r.json() as Frame & {error?:string;retryAfter?:number};if(c.signal.aborted)return;if(!r.ok){if(j.retryAfter)setRetryAt(Date.now()+j.retryAfter*1000);throw Error(j.error);}frameCache.set(key,{at:Date.now(),frame:j});if(frameCache.size>24)frameCache.delete(frameCache.keys().next().value!);setFrame(j);setLoading(false)}).catch(e=>{if(e.name!=='AbortError'){setError(e.name==='TimeoutError'?'The model download took too long. Please retry.':e.message);setLoading(false)}})},240);
  return()=>{clearTimeout(timer);c.abort()};
 },[run,model,hour,level,refresh,attempt]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tool={name:'select_forecast',title:'Select a stratosphere forecast',description:'Select model, pressure, lead time and field in the visible globe. Returns the selection; forecast data then loads. Direct ECMWF supports 10, 50 and 100 hPa; ECMWF via Open-Meteo supports 50 and 100. ICON has seven days; the other models have ten.',inputSchema:{type:'object',properties:{model:{type:'string',enum:Object.keys(MODELS)},level:{type:'integer',enum:levels},hour:{type:'integer',minimum:0,maximum:240,multipleOf:6},field:{type:'string',enum:['temperature','wind']}},required:['level','hour','field'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const v=input as {model?:string;level:number;hour:number;field:string},m=v?.model??model;if(!v||!isModel(m)||!supports(m,v.level)||!Number.isInteger(v.hour)||v.hour<0||v.hour>MODELS[m].maxHour||v.hour%6||!['temperature','wind'].includes(v.field))throw Error('Unsupported model, pressure level, forecast hour or field.');setModel(m);setLevel(v.level);setHour(v.hour);setField(v.field);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {status:'selected',model:m,level:v.level,hour:v.hour,field:v.field};}};
  try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[model]);
 const valid=run?new Date(Date.parse(run)+hour*3600000).toISOString():'';
 const matching=frame&&frame.hour===hour&&frame.level===level&&frame.run===run&&(frame.model??'gfs')===model;
 const previousName=frame&&isModel(frame.model??'gfs')?MODELS[(frame.model??'gfs') as ModelId].label:'';
 useEffect(()=>{if(!retryAt)return;const timer=setTimeout(()=>{setRetryAt(0);setAttempt(v=>v+1)},Math.max(0,retryAt-Date.now())),tick=setInterval(()=>setRetryTick(v=>v+1),1000);return()=>{clearTimeout(timer);clearInterval(tick)}},[retryAt]);
 const retrySeconds=retryTick>=0?Math.max(0,Math.ceil((retryAt-Date.now())/1000)):0;
 const initialLabel=model==='gfs'?'Analysis':model==='ecmwf_direct'?'Initial field':'Today · 00 UTC';
 const label=hour===0?initialLabel:`Forecast +${hour}h`;
 const documentation=model==='gfs'?'https://www.nco.ncep.noaa.gov/pmb/products/gfs/':model==='ecmwf_direct'?'https://www.ecmwf.int/en/forecasts/datasets/open-data':'https://open-meteo.com/en/docs';
 const method=model==='gfs'?'Direct GFS fields on a 1° grid from one model cycle.':model==='ecmwf_direct'?'Direct ECMWF IFS 0.25° fields from one completed 00 or 12 UTC run. Every fourth grid point is retained for a 1° display grid. These are native pressure-level fields, with no vertical interpolation.':'Point forecasts sampled on a 10° latitude–longitude grid, then bilinearly interpolated. This is a coarse hemispheric overview, not the model’s native resolution. The source combines successive model runs.';
 return <main className="atlas">
  <header className="topbar"><div className="brand"><Orbit size={31}/><span>stratoscope<span className="brand-mark"> / </span></span><span className="brand-sub">ATMOSPHERIC ATLAS</span></div><div className="hemisphere">NORTHERN HEMISPHERE <span>00°—90° N</span></div></header>
  <section className="workspace">
   <aside className="controls">
    <div className="eyebrow">THE STRATOSPHERE</div><h1>A view from <br/>above.</h1>
    <div className="model-control"><label className="section-label" id="model-label">Forecast model</label><Select value={model} onValueChange={chooseModel}><SelectTrigger aria-labelledby="model-label" className="model-trigger"><SelectValue/></SelectTrigger><SelectContent className="model-options">{Object.entries(MODELS).map(([id,c])=><SelectItem key={id} value={id}>{c.label}</SelectItem>)}</SelectContent></Select><p className="model-note">{config.note}</p></div>
    <div className="control-section"><span className="section-label"><Layers size={15}/> Pressure level <small>hPa</small></span>
     <RadioGroup className="level-list" aria-label="Pressure level" value={String(level)} onValueChange={v=>setLevel(Number(v))}>{levels.map(l=><label key={l} className={`level ${level===l?'selected':''} ${!supports(model,l)?'unavailable':''}`} title={!supports(model,l)?`Not available for ${config.label}`:undefined}><RadioGroupItem value={String(l)} disabled={!supports(model,l)} aria-label={`${l} hPa${!supports(model,l)?' unavailable':''}`} className="level-radio"/><span>{l}<small> hPa</small></span><span>{supports(model,l)?alt[l]:'—'}</span></label>)}</RadioGroup>
     <p className="muted footnote">{model==='ecmwf_direct'?'Direct ECMWF supplies 10, 50 and 100 hPa. Its open feed does not include 20, 30 or 70 hPa.':model==='ecmwf'?'Open-Meteo ECMWF supplies 50 and 100 hPa. Select ECMWF IFS · direct for 10 hPa.':model==='gfs'?'Lower pressure, higher altitude. Altitudes are approximate.':'Open-Meteo supplies levels down to 30 hPa. Direct ECMWF and GFS also provide 10 hPa.'}</p>
    </div>
    <div className="control-section overlay-controls"><span className="section-label">Map layers</span><label className="toggle-row">Height contours <Switch checked={contours} onCheckedChange={setContours} aria-label="Height contours"/></label><label className="toggle-row">Latitude & longitude <Switch checked={grid} onCheckedChange={setGrid} aria-label="Latitude and longitude"/></label></div>
    <div className="source-card"><span className="source-label">DATA SOURCE</span><strong>{config.resolution}</strong><span className="muted">{config.provider}</span><div className="run-meta">{run?`${cyclic?'Run: ':'Timeline: '}${date(run)} UTC`:'Finding latest forecast'}</div>{!cyclic&&<span className="rolling-note">Rolling forecast, not a fixed model run</span>}<button className="text-button" onClick={refreshData}><RefreshCw size={13}/> Refresh data</button></div>
   </aside>
   <div className="plot-area"><div className="plot-heading"><div><span className="eyebrow">INTERACTIVE 3D GLOBE</span><h2>{level} hPa <span>/ {field==='temperature'?'Temperature':'Wind speed'}</span></h2></div><Tabs value={field} onValueChange={setField}><TabsList className="field-tabs"><TabsTrigger value="temperature">Temperature</TabsTrigger><TabsTrigger value="wind">Wind</TabsTrigger></TabsList></Tabs></div>
    <div className="map-shell"><PolarMap frame={frame} field={field} contours={contours} graticule={grid}/>{loading&&<div className="map-status" role="status"><RefreshCw size={14} className="spin"/> Loading {config.label} · {level} hPa{model!=='gfs'?' · first download may take a moment':''}</div>}{error&&<div className="map-error" role="alert"><strong>{retryAt?'Download paused':'Forecast unavailable'}</strong><span>{error}</span>{retryAt?<span>Resuming in {retrySeconds} seconds</span>:<button onClick={refreshData}>Try again</button>}</div>}{frame&&!matching&&<div className="previous-label">Previous plot: {previousName} · {frame.level} hPa · {date(frame.valid)} UTC</div>}</div>
    <div className="legend"><div><span>{field==='temperature'?'TEMPERATURE':'WIND SPEED'}</span><span>{field==='temperature'?'°C':'m/s'}</span></div><div className={`color-ramp ${field==='wind'?'wind-ramp':''}`}/><div className="legend-ticks">{(field==='temperature'?[-90,-75,-60,-45,-30,-15,0]:[0,20,40,60,80,100,120]).map(v=><span key={v}>{v}</span>)}</div></div>
   </div>
   <aside className="readout"><div className="eyebrow">VALID AT</div><h3>{valid?new Date(valid).toLocaleDateString('en-GB',{timeZone:'UTC',day:'numeric',month:'long'}):'—'}</h3><div className="valid-hour">{valid?valid.slice(11,16):'—'} <span>UTC</span></div><span className="forecast-badge">{label}</span><div className="readout-rule"/><div className="eyebrow">EXPLORE THE GLOBE</div><p>Drag in any direction to turn the Earth. Scroll or pinch to move closer.</p><div className="contour-key"><span/> Geopotential height</div><p className="muted">Contours every 400 m, labelled in decametres (dam).</p><p className="muted">Only the Northern Hemisphere has weather data. The unshaded south is outside this viewer’s coverage.</p><details><summary><Info size={14}/> Data & method</summary><p>{config.provider}. {method}</p>{model==='ecmwf_direct'&&<p>Contains modified ECMWF forecast data (2026), supplied under CC BY 4.0. The display samples and converts the original fields; ECMWF does not endorse this viewer.</p>}{model==='ecmwf'&&<p>Open-Meteo ECMWF IFS 0.25° supplies 50 and 100 hPa. Select the direct ECMWF source for 10 hPa.</p>}<p>The timeline uses six-hour steps{cyclic?', measured from the model initialization time. The initial field is forecast hour zero.':', measured from today at 00 UTC, not from a model initialisation time. Open-Meteo timelines are cached for up to 30 minutes.'}</p><p>Globe lighting gives depth; use the pointer values for precise numbers. Arrow keys rotate, +/− zoom and Home restores the north-pole view.</p><p>Model forecasts are not observations. Coastlines: Natural Earth.</p><a href={documentation} target="_blank" rel="noreferrer">{model==='gfs'?'NOAA documentation':model==='ecmwf_direct'?'ECMWF data & licence':'Weather data by Open-Meteo'}</a>{frame?.fetchedAt&&<p>Map downloaded {date(frame.fetchedAt)} UTC.</p>}</details></aside>
  </section>
  <section className="timeline" aria-label="Forecast timeline"><div className="timeline-title"><span className="eyebrow">FORECAST TIMELINE</span><strong>{hour===0?initialLabel:`+${hour} hours`}<span> / {maxHour/24} days</span></strong></div><div className="step-buttons"><button aria-label="Previous forecast" disabled={hour===0} onClick={()=>setHour(v=>Math.max(0,v-6))}><ChevronLeft size={20}/></button><button aria-label="Next forecast" disabled={hour===maxHour} onClick={()=>setHour(v=>Math.min(maxHour,v+6))}><ChevronRight size={20}/></button></div><div className="timeline-track"><Slider aria-label="Forecast hour" value={[hour]} min={0} max={maxHour} step={6} onValueChange={v=>setHour(v[0])}/><div className="day-ticks">{Array.from({length:maxHour/24+1},(_,i)=><button key={i} onClick={()=>setHour(i*24)} className={hour===i*24?'active':''}>{i===0?(cyclic?'Run':'00Z'):`+${i}d`}</button>)}</div></div></section>
  <footer><span>STRATOSCOPE <b> / </b> NORTHERN HEMISPHERE</span><span>{model==='gfs'?'NOAA / NCEP':model==='ecmwf_direct'?<a href="https://www.ecmwf.int/en/forecasts/datasets/open-data" target="_blank" rel="noreferrer">ECMWF · CC BY 4.0</a>:<a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Weather data by Open-Meteo</a>} <i>·</i> All times UTC</span></footer>
 </main>
}

