'use client';
import {useEffect,useState} from 'react';
import {Orbit,RefreshCw,Layers,ChevronLeft,ChevronRight,Info} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {PolarMap} from '@/components/polar-map';
import type {Frame} from '@/lib/grib';
const levels=[10,20,30,50,70,100];
const frameCache=new Map<string,Frame>();
const alt:Record<number,string>={10:'~31 km',20:'~26 km',30:'~24 km',50:'~21 km',70:'~18 km',100:'~16 km'};
const date=(v:string)=>new Date(v).toLocaleString('en-GB',{timeZone:'UTC',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:false}).replace(',','');
export default function Home(){
 const [run,setRun]=useState(''),[level,setLevel]=useState(10),[hour,setHour]=useState(0),[field,setField]=useState('temperature'),[contours,setContours]=useState(true),[grid,setGrid]=useState(true),[frame,setFrame]=useState<Frame|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');fetch('/api/forecast?meta=1',{signal:c.signal,cache:'no-cache'}).then(async r=>{const j=await r.json() as Frame & {error?:string};if(!r.ok)throw Error(j.error);setRun(j.run)}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false)}});return()=>c.abort()},[refresh]);
 useEffect(()=>{
  if(!run)return;const c=new AbortController(),key=`${run}/${level}/${hour}`,cached=frameCache.get(key);setError('');
  if(cached){setFrame(cached);setLoading(false);return;}setLoading(true);
  const timer=setTimeout(()=>{fetch(`/api/forecast?run=${encodeURIComponent(run)}&hour=${hour}&level=${level}`,{signal:AbortSignal.any([c.signal,AbortSignal.timeout(35000)])}).then(async r=>{const j=await r.json() as Frame & {error?:string};if(!r.ok)throw Error(j.error);frameCache.set(key,j);if(frameCache.size>24)frameCache.delete(frameCache.keys().next().value!);setFrame(j);setLoading(false)}).catch(e=>{if(e.name!=='AbortError'){setError(e.name==='TimeoutError'?'NOAA is taking longer than expected. Please retry.':e.message);setLoading(false)}})},220);
  return()=>{clearTimeout(timer);c.abort()};
 },[run,hour,level,refresh]);
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tool={name:'select_forecast',title:'Select a stratosphere forecast',description:'Select the visible pressure level, forecast lead time and field. Returns the selection; NOAA data then loads in the chart.',inputSchema:{type:'object',properties:{level:{type:'integer',enum:levels},hour:{type:'integer',minimum:0,maximum:240,multipleOf:6},field:{type:'string',enum:['temperature','wind']}},required:['level','hour','field'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const v=input as {level:number;hour:number;field:string};if(!v||!levels.includes(v.level)||!Number.isInteger(v.hour)||v.hour<0||v.hour>240||v.hour%6||!['temperature','wind'].includes(v.field))throw Error('Invalid pressure level, forecast hour or field.');setLevel(v.level);setHour(v.hour);setField(v.field);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {status:'selected',level:v.level,hour:v.hour,field:v.field};}};
  try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[]);
 const valid=run?new Date(Date.parse(run)+hour*3600000).toISOString():'';
 return <main className="atlas"><header className="topbar"><div className="brand"><Orbit size={31}/><span>stratoscope<span className="brand-mark"> / </span></span><span className="brand-sub">ATMOSPHERIC ATLAS</span></div><div className="hemisphere">NORTHERN HEMISPHERE <span>00°—90° N</span></div></header>
 <section className="workspace"><aside className="controls"><div className="eyebrow">THE STRATOSPHERE</div><h1>A view from <br/>above.</h1><div className="control-section"><span className="section-label"><Layers size={15}/> Pressure level <small>hPa</small></span><RadioGroup className="level-list" aria-label="Pressure level" value={String(level)} onValueChange={v=>setLevel(Number(v))}>{levels.map(l=><label key={l} className={`level ${level===l?'selected':''}`}><RadioGroupItem value={String(l)} aria-label={`${l} hPa`} className="level-radio"/><span>{l}<small> hPa</small></span><span>{alt[l]}</span></label>)}</RadioGroup><p className="muted footnote">Lower pressure, higher altitude.<br/>Altitudes are approximate.</p></div><div className="control-section"><span className="section-label">Map layers</span><label className="toggle-row">Height contours <Switch checked={contours} onCheckedChange={setContours} aria-label="Height contours"/></label><label className="toggle-row">Latitude & longitude <Switch checked={grid} onCheckedChange={setGrid} aria-label="Latitude and longitude"/></label></div><div className="source-card"><span className="source-label">FORECAST MODEL</span><strong>NOAA GFS <span>1°</span></strong><span className="muted">Global Forecast System</span><div className="run-meta">{run?`${date(run)} UTC`:'Finding latest complete run'}</div><button className="text-button" onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={13}/> Refresh run</button></div></aside>
 <div className="plot-area"><div className="plot-heading"><div><span className="eyebrow">POLAR STEREOGRAPHIC</span><h2>{level} hPa <span>/ {field==='temperature'?'Temperature':'Wind speed'}</span></h2></div><Tabs value={field} onValueChange={setField}><TabsList className="field-tabs"><TabsTrigger value="temperature">Temperature</TabsTrigger><TabsTrigger value="wind">Wind</TabsTrigger></TabsList></Tabs></div><div className="map-shell"><PolarMap frame={frame} field={field} contours={contours} graticule={grid}/>{loading&&<div className="map-status" role="status"><RefreshCw size={14} className="spin"/> Loading {level} hPa · +{hour}h</div>}{error&&<div className="map-error" role="alert"><strong>Forecast unavailable</strong><span>{error}</span><button onClick={()=>setRefresh(v=>v+1)}>Try again</button></div>}{frame&&(frame.hour!==hour||frame.level!==level||frame.run!==run)&&<div className="previous-label">Previous plot: {frame.level} hPa · {date(frame.valid)} UTC</div>}</div><div className="legend"><div><span>{field==='temperature'?'TEMPERATURE':'WIND SPEED'}</span><span>{field==='temperature'?'°C':'m/s'}</span></div><div className={`color-ramp ${field==='wind'?'wind-ramp':''}`}/><div className="legend-ticks">{(field==='temperature'?[-90,-75,-60,-45,-30,-15,0]:[0,20,40,60,80,100,120]).map(v=><span key={v}>{v}</span>)}</div></div></div>
 <aside className="readout"><div className="eyebrow">VALID AT</div><h3>{valid?new Date(valid).toLocaleDateString('en-GB',{timeZone:'UTC',day:'numeric',month:'long'}):'—'}</h3><div className="valid-hour">{valid?valid.slice(11,16):'—'} <span>UTC</span></div><span className="forecast-badge">{hour===0?'Analysis':`Forecast +${hour}h`}</span><div className="readout-rule"/><div className="eyebrow">READING THE MAP</div><p>Colours show {field==='temperature'?'air temperature':'wind speed'} on the selected pressure surface.</p><div className="contour-key"><span/> Geopotential height</div><p className="muted">Contours every 400 m, labelled in decametres (dam).</p><div className="north-key">N<span>90°</span></div><p className="muted">North Pole at the centre.<br/>Equator at the outer edge.</p><details><summary><Info size={14}/> Data & method</summary><p>NOAA GFS on a 1° grid, bilinearly interpolated for display. The latest complete run is checked when you open or refresh. Forecast steps are 6 hours.</p><p>GFS provides 10 hPa directly. Model forecasts are not observations. Coastlines: Natural Earth.</p><a href="https://www.nco.ncep.noaa.gov/pmb/products/gfs/" target="_blank" rel="noreferrer">NOAA documentation</a></details></aside></section>
 <section className="timeline" aria-label="Forecast timeline"><div className="timeline-title"><span className="eyebrow">FORECAST TIMELINE</span><strong>{hour===0?'Analysis':`+${hour} hours`}<span> / 10 days</span></strong></div><div className="step-buttons"><button aria-label="Previous forecast" disabled={hour===0} onClick={()=>setHour(v=>Math.max(0,v-6))}><ChevronLeft size={20}/></button><button aria-label="Next forecast" disabled={hour===240} onClick={()=>setHour(v=>Math.min(240,v+6))}><ChevronRight size={20}/></button></div><div className="timeline-track"><Slider aria-label="Forecast hour" value={[hour]} min={0} max={240} step={6} onValueChange={v=>setHour(v[0])}/><div className="day-ticks">{Array.from({length:11},(_,i)=><button key={i} onClick={()=>setHour(i*24)} className={hour===i*24?'active':''}>{i===0?'Run':`+${i}d`}</button>)}</div></div></section><footer><span>STRATOSCOPE <b> / </b> NORTHERN HEMISPHERE</span><span>NOAA / NCEP <i>·</i> All times UTC <i>·</i> 100—10 hPa</span></footer></main>
}




