'use client';
import {useEffect,useRef,useState} from 'react';
import type {Frame} from '@/lib/grib';
const S=760,C=S/2,R=340,rad=Math.PI/180;
const tempStops=[[43,24,79],[58,52,144],[57,99,197],[61,165,192],[141,205,196],[234,205,127],[236,112,76]];
const windStops=[[22,43,67],[30,91,121],[42,148,161],[100,195,169],[207,213,123],[238,155,76],[203,70,93]];
export function sample(f:Frame,values:number[],lat:number,lon:number){const g=f.grid,x=((lon-g.lon0)/g.dx%g.nx+g.nx)%g.nx,y=Math.max(0,Math.min(g.ny-1,(lat-g.lat0)/g.dy)),i=Math.floor(x),j=Math.floor(y),a=x-i,b=y-j,j2=Math.min(g.ny-1,j+1);return (values[j*g.nx+i]*(1-a)+values[j*g.nx+(i+1)%g.nx]*a)*(1-b)+(values[j2*g.nx+i]*(1-a)+values[j2*g.nx+(i+1)%g.nx]*a)*b;}
function inverse(x:number,y:number){const dx=(x-C)/R,dy=(y-C)/R,r=Math.hypot(dx,dy);return {lat:90-2*Math.atan(r)/rad,lon:Math.atan2(dx,dy)/rad,r};}
function project(lon:number,lat:number){const r=R*Math.tan((90-lat)*rad/2);return [C+r*Math.sin(lon*rad),C+r*Math.cos(lon*rad)];}
export function PolarMap({frame,field,contours,graticule}:{frame:Frame|null;field:string;contours:boolean;graticule:boolean}){
 const ref=useRef<HTMLCanvasElement>(null),[coast,setCoast]=useState<number[][][]>([]),[point,setPoint]=useState<{lat:number;lon:number}|null>(null);
 useEffect(()=>{fetch('/coastline.json').then(r=>r.json() as Promise<{features:any[]}>).then(j=>setCoast(j.features.flatMap((f:any)=>f.geometry.type==='LineString'?[f.geometry.coordinates]:f.geometry.coordinates))).catch(()=>{})},[]);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,S,S);ctx.fillStyle='#10232d';ctx.beginPath();ctx.arc(C,C,R,0,Math.PI*2);ctx.fill();
 if(frame){const img=ctx.createImageData(S,S),stops=field==='temperature'?tempStops:windStops;for(let y=39;y<S-39;y++)for(let x=39;x<S-39;x++){const p=inverse(x,y);if(p.r>1)continue;const v=field==='temperature'?sample(frame,frame.temperature,p.lat,p.lon):Math.hypot(sample(frame,frame.u,p.lat,p.lon),sample(frame,frame.v,p.lat,p.lon));const a=Math.max(0,Math.min(5.999,(field==='temperature'?(v+90)/90:v/120)*6)),i=Math.floor(a),t=a-i,k=(y*S+x)*4;for(let c=0;c<3;c++)img.data[k+c]=Math.round(stops[i][c]*(1-t)+stops[i+1][c]*t);img.data[k+3]=255;}ctx.putImageData(img,0,0);}
 ctx.save();ctx.beginPath();ctx.arc(C,C,R,0,Math.PI*2);ctx.clip();
 if(graticule){ctx.strokeStyle='#d3efff30';ctx.lineWidth=.8;ctx.setLineDash([3,5]);for(const lat of [0,30,60,80]){const r=R*Math.tan((90-lat)*rad/2);ctx.beginPath();ctx.arc(C,C,r,0,Math.PI*2);ctx.stroke();}for(let lon=-180;lon<180;lon+=30){const [x,y]=project(lon,0);ctx.beginPath();ctx.moveTo(C,C);ctx.lineTo(x,y);ctx.stroke();}ctx.setLineDash([]);}
 ctx.strokeStyle='#d9f1ff88';ctx.lineWidth=.9;for(const line of coast){ctx.beginPath();let started=false;for(const [lon,lat] of line){if(lat<0){started=false;continue}const [x,y]=project(lon,lat);if(!started){ctx.moveTo(x,y);started=true}else ctx.lineTo(x,y);}ctx.stroke();}
 if(frame&&contours){const step=6,n=Math.ceil(S/step)+1,vals=new Float32Array(n*n);for(let j=0;j<n;j++)for(let i=0;i<n;i++){const p=inverse(i*step,j*step);vals[j*n+i]=p.r<=1?sample(frame,frame.height,p.lat,p.lon):NaN;}
 const min=Math.ceil(Math.min(...frame.height)/400)*400,max=Math.max(...frame.height);ctx.lineWidth=1.1;ctx.strokeStyle='#fff7ddaa';ctx.font='12px Arial';const labels:{x:number;y:number;text:string}[]=[];
 for(let h=min;h<=max;h+=400){ctx.beginPath();let segments=0;for(let j=0;j<n-1;j++)for(let i=0;i<n-1;i++){const v=[vals[j*n+i],vals[j*n+i+1],vals[(j+1)*n+i+1],vals[(j+1)*n+i]],xy=[[i*step,j*step],[(i+1)*step,j*step],[(i+1)*step,(j+1)*step],[i*step,(j+1)*step]];if(v.some(a=>!Number.isFinite(a)))continue;const cross:number[][]=[];for(let k=0;k<4;k++){const k2=(k+1)%4;if((v[k]<h)!==(v[k2]<h)){const t=(h-v[k])/(v[k2]-v[k]);cross.push([xy[k][0]+t*(xy[k2][0]-xy[k][0]),xy[k][1]+t*(xy[k2][1]-xy[k][1])]);}}for(let k=0;k+1<cross.length;k+=2){ctx.moveTo(...cross[k] as [number,number]);ctx.lineTo(...cross[k+1] as [number,number]);segments++;if(segments%180===50&&labels.every(l=>Math.hypot(l.x-cross[k][0],l.y-cross[k][1])>90))labels.push({x:cross[k][0],y:cross[k][1],text:String(h/10)});}}ctx.stroke();}
 for(const l of labels){ctx.fillStyle='#122334db';ctx.fillRect(l.x-18,l.y-8,36,16);ctx.fillStyle='#fff1d2';ctx.textAlign='center';ctx.fillText(l.text,l.x,l.y+4);}}
 ctx.restore();ctx.strokeStyle='#b9d4e042';ctx.lineWidth=1;ctx.beginPath();ctx.arc(C,C,R,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#9bb5c5';ctx.font='13px monospace';ctx.textAlign='center';ctx.textBaseline='middle';for(const lon of [-180,-120,-60,0,60,120]){const [x,y]=project(lon,-3);ctx.fillText(lon===0?'0°':`${Math.abs(lon)}°${lon===-180?'':lon<0?'W':'E'}`,x,y);}ctx.fillStyle='#f3f5e9';ctx.font='11px monospace';if(graticule)for(const lat of [30,60]){const [x,y]=project(90,lat);ctx.fillText(lat+'°N',x,y-9);}ctx.strokeStyle='#e5f4ff';ctx.beginPath();ctx.moveTo(C-4,C);ctx.lineTo(C+4,C);ctx.moveTo(C,C-4);ctx.lineTo(C,C+4);ctx.stroke();
 },[frame,field,contours,graticule,coast]);
 return <div className="polar-map"><canvas ref={ref} width={S} height={S} aria-label={frame?`${frame.level} hPa ${field} polar map valid ${frame.valid}`:'Northern Hemisphere map loading'} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect(),p=inverse((e.clientX-r.left)*S/r.width,(e.clientY-r.top)*S/r.height);setPoint(p.r<=1?p:null)}} onPointerLeave={()=>setPoint(null)}/>{frame&&point&&<div className="probe"><span>{point.lat.toFixed(1)}°N · {Math.abs(point.lon).toFixed(1)}°{point.lon<0?'W':'E'}</span><b>{field==='temperature'?sample(frame,frame.temperature,point.lat,point.lon).toFixed(1)+' °C':Math.hypot(sample(frame,frame.u,point.lat,point.lon),sample(frame,frame.v,point.lat,point.lon)).toFixed(1)+' m/s'}</b><span>{(sample(frame,frame.height,point.lat,point.lon)/10).toFixed(0)} dam</span></div>}</div>
}

