'use client';
import {useEffect,useRef,useState} from 'react';
import {Plus,Minus,Compass,RotateCcw} from 'lucide-react';
import type {Frame} from '@/lib/grib';
import {createRenderer,SIZE,CENTER,RADIUS,viewBasis,rotateBasis,projectGlobe,inverseGlobe,sample,sampleWind,color} from '@/lib/globe';
export function PolarMap({frame,field,contours,graticule}:{frame:Frame|null;field:string;contours:boolean;graticule:boolean}){
 const base=useRef<HTMLCanvasElement>(null),overlay=useRef<HTMLCanvasElement>(null),renderer=useRef<ReturnType<typeof createRenderer>>(null),coast=useRef<number[][][]>([]),view=useRef({basis:viewBasis(),zoom:1}),raf=useRef(0),paint=useRef(()=>{}),pointers=useRef(new Map<number,{x:number;y:number}>()),pinch=useRef(0);
 const [probe,setProbe]=useState<{lat:number;lon:number}|null>(null),[position,setPosition]=useState('65°N · 0°E'),[dragging,setDragging]=useState(false),[software,setSoftware]=useState(false);
 const request=()=>{if(!raf.current)raf.current=requestAnimationFrame(()=>{raf.current=0;paint.current()})};
 function move(dx:number,dy:number){view.current.basis=rotateBasis(view.current.basis,dx,dy);setProbe(null);request()}
 function zoom(factor:number){view.current.zoom=Math.max(.72,Math.min(2.4,view.current.zoom*factor));request()}
 function reset(north:boolean){view.current={basis:viewBasis(north?90:65),zoom:1};setProbe(null);request()}
 paint.current=()=>{
  const canvas=overlay.current,ctx=canvas?.getContext('2d');if(!ctx)return;const {basis:b,zoom:z}=view.current,wind=field==='wind';ctx.clearRect(0,0,SIZE,SIZE);
  if(renderer.current)renderer.current.draw(frame,b,z,wind,contours);
  else{
   const small=document.createElement('canvas');small.width=small.height=380;const c=small.getContext('2d')!,img=c.createImageData(380,380);
   for(let y=0;y<380;y++)for(let x=0;x<380;x++){const p=inverseGlobe(x*2,y*2,b,z);if(!p)continue;const k=(y*380+x)*4;let rgb=[13,28,38];if(frame&&p.lat>=0){const val=wind?sampleWind(frame,p.lat,p.lon):sample(frame,frame.temperature,p.lat,p.lon);rgb=color(val,wind,frame.ensemble?.view==='spread');if(contours&&Math.abs(sample(frame,frame.height,p.lat,p.lon)/400-Math.round(sample(frame,frame.height,p.lat,p.lon)/400))<.012)rgb=[220,225,210];}rgb.forEach((v,i)=>img.data[k+i]=v*(.72+.28*p.z));img.data[k+3]=255;}c.putImageData(img,0,0);ctx.drawImage(small,0,0,SIZE,SIZE);
  }
  const line=(points:number[][])=>{ctx.beginPath();let started=false;for(const [lon,lat] of points){const p=projectGlobe(lon,lat,b,z);if(p.depth<=.005){started=false;continue}if(started)ctx.lineTo(p.x,p.y);else{ctx.moveTo(p.x,p.y);started=true}}ctx.stroke()};
  if(graticule){ctx.lineWidth=.7;ctx.strokeStyle='#daf4ff38';ctx.setLineDash([3,5]);for(const lat of [-60,-30,0,30,60,80])line(Array.from({length:181},(_,i)=>[i*2-180,lat]));for(let lon=-180;lon<180;lon+=30)line(Array.from({length:91},(_,i)=>[lon,i*2-90]));ctx.setLineDash([]);}
  ctx.strokeStyle='#e5f7ff83';ctx.lineWidth=.85;coast.current.forEach(line);
  ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='12px Arial';
  if(frame&&contours){const labels:{x:number;y:number}[]=[];for(let lat=15;lat<=85;lat+=10)for(let lon=-180;lon<180;lon+=5){const a=sample(frame,frame.height,lat,lon),c=sample(frame,frame.height,lat,lon+5),h=Math.ceil(Math.min(a,c)/400)*400;if(h>=Math.max(a,c)||a===c)continue;const p=projectGlobe(lon+5*(h-a)/(c-a),lat,b,z);if(p.depth<.25||p.x<35||p.x>SIZE-35||p.y<35||p.y>SIZE-35||labels.some(q=>Math.hypot(p.x-q.x,p.y-q.y)<125))continue;labels.push(p);ctx.fillStyle='#132731df';ctx.fillRect(p.x-18,p.y-8,36,16);ctx.fillStyle='#fff3d9';ctx.fillText(String(h/10),p.x,p.y);}}
  for(const [lon,lat,text] of [[0,90,'N'],[0,0,'0°'],[90,60,'60°N'],[-90,30,'30°N']] as [number,number,string][]){const p=projectGlobe(lon,lat,b,z);if(p.depth>.2){ctx.fillStyle='#e1f5ff';ctx.fillText(text,p.x,p.y-9);}}
  const lat=Math.asin(Math.max(-1,Math.min(1,b.front[1])))*180/Math.PI,lon=Math.atan2(b.front[0],b.front[2])*180/Math.PI;setPosition(`${Math.abs(lat).toFixed(0)}°${lat<0?'S':'N'} · ${Math.abs(lon).toFixed(0)}°${lon<0?'W':'E'} · ${z.toFixed(1)}×`);
 };
 useEffect(()=>{try{renderer.current=createRenderer(base.current!);setSoftware(!renderer.current)}catch{renderer.current=null;setSoftware(true)}fetch('/coastline.json').then(r=>r.json() as Promise<{features:{geometry:{type:string;coordinates:number[][]|number[][][]}}[]}>).then(j=>{coast.current=j.features.flatMap(f=>f.geometry.type==='LineString'?[f.geometry.coordinates as number[][]]:f.geometry.coordinates as number[][][]);request()}).catch(()=>{});request();const c=overlay.current!;const wheel=(e:WheelEvent)=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();zoom(Math.exp(-e.deltaY*.0015))};c.addEventListener('wheel',wheel,{passive:false});return()=>{cancelAnimationFrame(raf.current);renderer.current?.dispose();c.removeEventListener('wheel',wheel)}},[]);
 useEffect(request,[frame,field,contours,graticule]);
 const release=(id:number)=>{pointers.current.delete(id);pinch.current=0;if(!pointers.current.size)setDragging(false)};
 return <div className="globe-wrap"><div className="globe-tools"><div><button aria-label="Zoom in" onClick={()=>zoom(1.15)}><Plus size={17}/></button><button aria-label="Zoom out" onClick={()=>zoom(1/1.15)}><Minus size={17}/></button></div><div><button aria-label="Reset to north pole" title="North-pole view" onClick={()=>reset(true)}><Compass size={17}/><span>North pole</span></button><button aria-label="Reset tilted globe" title="Reset tilted view" onClick={()=>reset(false)}><RotateCcw size={16}/></button></div></div><div className={`polar-map globe ${dragging?'dragging':''}`}><canvas ref={base} width={SIZE} height={SIZE} aria-hidden="true"/><canvas ref={overlay} width={SIZE} height={SIZE} className="globe-overlay" tabIndex={0} role="img" aria-label={`${frame?frame.level+' hPa '+field+' '+(frame.ensemble?.view??'')+' globe, valid '+frame.valid:'Globe loading'}. Drag to rotate and tilt. Left and right arrows step forecast time. Shift plus arrows rotate; plus and minus zoom; Home resets north.`}
 onPointerDown={e=>{e.currentTarget.focus({preventScroll:true});e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});setDragging(true);setProbe(null);pinch.current=0}}
 onPointerMove={e=>{const active=pointers.current.get(e.pointerId);if(active){pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===2){const [a,b]=Array.from(pointers.current.values()),dist=Math.hypot(a.x-b.x,a.y-b.y);if(pinch.current)zoom(dist/pinch.current);pinch.current=dist;}else{const scale=130/e.currentTarget.getBoundingClientRect().width;move((e.clientX-active.x)*scale,(e.clientY-active.y)*scale)}}else{const r=e.currentTarget.getBoundingClientRect(),p=inverseGlobe((e.clientX-r.left)*SIZE/r.width,(e.clientY-r.top)*SIZE/r.height,view.current.basis,view.current.zoom);setProbe(p)}}}
 onPointerUp={e=>release(e.pointerId)} onPointerCancel={e=>release(e.pointerId)} onLostPointerCapture={e=>release(e.pointerId)} onPointerLeave={()=>{if(!pointers.current.size)setProbe(null)}}
 onKeyDown={e=>{const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home'];if(e.altKey||e.ctrlKey||e.metaKey||!keys.includes(e.key)||(['ArrowLeft','ArrowRight'].includes(e.key)&&!e.shiftKey))return;e.preventDefault();e.stopPropagation();if(e.key==='Home')reset(true);else if(e.key==='+'||e.key==='=')zoom(1.15);else if(e.key==='-')zoom(1/1.15);else move(e.key==='ArrowLeft'?-8:e.key==='ArrowRight'?8:0,e.key==='ArrowUp'?-8:e.key==='ArrowDown'?8:0)}}/>
 {frame&&probe&&<div className="probe"><span>{Math.abs(probe.lat).toFixed(1)}°{probe.lat<0?'S':'N'} · {Math.abs(probe.lon).toFixed(1)}°{probe.lon<0?'W':'E'}</span>{probe.lat>=0?<><b>{frame.ensemble?.view==='spread'?'σ ':''}{field==='temperature'?sample(frame,frame.temperature,probe.lat,probe.lon).toFixed(1)+' °C':sampleWind(frame,probe.lat,probe.lon).toFixed(1)+' m/s'}</b><span>{frame.ensemble&&frame.ensemble.view!=='member'?'Mean ':''}{(sample(frame,frame.height,probe.lat,probe.lon)/10).toFixed(0)} dam</span></>:<b>No data south of the equator</b>}</div>}</div><div className="globe-caption"><span>Drag to rotate · Ctrl + scroll or pinch to zoom</span><output aria-label="Globe orientation">{position}</output></div>{software&&<span className="software-note">Globe using software rendering</span>}</div>
}
